# Generated by Django 3.2.22 on 2023-11-22 19:10

from django.db import migrations


def update_field(apps, schema_editor):
    Order = apps.get_model('checkout', 'Order')
    for obj in Order.objects.all():
        obj.ooriginal_bag = 'original_bag'
        obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20231122_1858'),
    ]

    operations = [
        migrations.RunPython(update_field),
    ]
