# Generated by Django 3.2.22 on 2023-11-22 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20231122_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ooriginal_bag',
            new_name='original_bag',
        ),
    ]
